algo_config:
  algorithm: sb3_hrl.HIRO
  algo_kwargs:
    policy: MultiInputPolicy
    learning_rate: 1.11e-5
    buffer_size: 1_000_000
    learning_starts: 10_000
    batch_size: 4000
    tau: 0.01
    gamma: 0.99
    train_freq: 8
    gradient_steps: 8
    subgoal_freq: 60
    manager_exploration_noise: 0.1
    worker_exploration_noise: 0
    correction_candidate_count: 5
    correction_noise_scale: 0.5
    correction_action_sigma: 0.2
    stats_window_size: 100
    manager_kwargs:
      policy_kwargs:
        net_arch: [512, 512, 512]
    worker_kwargs:
      policy_kwargs:
        net_arch: [512, 512, 512]
    verbose: 1

learn_config:
  total_timesteps: 15_000_000
  progress_bar: true

vec_config:
  n_envs: 20
  vec_env_cls: SubprocVecEnv
  vec_env_kwargs: { "start_method": "spawn" }

callback_config:
  eval_callback_config:
    eval_freq: 2_500
    n_eval_episodes: 100
    log_path: eval

  ckpt_callback_config:
    save_freq: 20_000
    save_path: ckpts
    name_prefix: ckpt
    save_replay_buffer: false
    verbose: 0

  video_recorder_callback_config:
    render_freq: 20_000
    save_dir: ckpts
    name_prefix: video
