config_class: hrl_tl.config.train.HiroTrainingConfig
experiment_id: 4.a
models_dir: out/fourroom/hiro
model_name: hiro_fourroom
model_filename: model.pt
log_dir: log
tb_dir: tb
eval_dir: eval
config_dir: configs/fourroom
env_config_file: env/full_rand_ag_rand_gl_rand_obs_clear_dw.yaml
algo_config_file: baseline/hiro.yaml
num_runs: 1
retrain_model: false
rendering: false
verbose: false
