spec_rep_class: hrl_tl.wrappers.utils.spec_rep.CPCParamLv1MinimalSpecRep
spec_rep_args:
  num_clauses: 1
  args:
    L_gain:
      range: [ 0.5, 11 ]
      num_discrete_bins: 22
    k_steepness:
      range: [ 0.5, 10.0 ]
      num_discrete_bins: 20
    eps_margin:
      range: [ 0.0, 5.0 ]
      num_discrete_bins: 11
low_level_policy_class: hrl_tl.wrappers.low_level_policies.cpc.CPCLowLevelPolicy
low_level_policy_args:
  model_path: out/zone/cpc/pr/8.f.b/cpc_40.0M/rep_0/ckpts/ckpt_20000000_steps.zip
  var_value_info_generator_cls: hrl_tl.envs.tl_zone.ZoneVarValueInfoGenerator
  device: cuda:2
  goal_rep: one_hot
  algo: SDSAC
  verbose: false
max_low_level_policy_steps: 40
all_formulae_file_path: assets/formulae/zone/cpc/all_formulae_1_cla_1_max_pred_core.json
invalid_tl_action: random
tl_wrapper_args: configs/zone/cpc/wrapper/tl_wrapper_button_0.25.yaml
excluded_obs_keys: ["subtask"]
verbose: false
