study_name: ppo_zone
db_filename: ppo_zone.db
db_dir: db
total_timesteps: 1000000
n_trials: 20
n_startup_trials: 5
n_evaluations: 5
n_eval_episodes: 100
n_jobs: 2
parallel_backend: process
launch_dashboard: false
dashboard_port: 8080

tune_params:
  - name: batch_size
    target: algo_kwargs.batch_size
    suggest_type: categorical
    choices: [1000, 2000, 4000, 8000]

  - name: learning_rate
    target: algo_kwargs.learning_rate
    suggest_type: float
    low: 0.00001
    high: 0.001
    log: true

  - name: n_epochs
    target: algo_kwargs.n_epochs
    suggest_type: categorical
    choices: [10, 20, 40]

