study_name: spec_cond_sub_fetch
db_filename: spec_cond_sub_fetch.db
db_dir: db
total_timesteps: 1000000
n_trials: 50
n_startup_trials: 5
n_evaluations: 5
n_eval_episodes: 100
n_jobs: 1
parallel_backend: process
launch_dashboard: false
dashboard_port: 8080

tune_params:
  - name: batch_size
    target: algo_kwargs.batch_size
    suggest_type: int
    low: 1000
    high: 4000
    step: 1000

  - name: target_entropy
    target: algo_kwargs.target_entropy
    suggest_type: float
    low: 0.001
    high: 10.0
    log: true

  - name: ent_coef
    target: algo_kwargs.ent_coef
    suggest_type: categorical
    choices: ["auto_0.001", "auto_0.005", "auto_0.01", "auto_0.05", "auto_0.1"]

  - name: learning_rate
    target: algo_kwargs.learning_rate
    suggest_type: float
    low: 0.00001
    high: 0.001
    log: true

  - name: tau
    target: algo_kwargs.tau
    suggest_type: float
    low: 0.0001
    high: 1.0
    log: true

  - name: beta
    target: algo_kwargs.beta
    suggest_type: float
    low: 0.0
    high: 1.0

  - name: clip_range
    target: algo_kwargs.clip_range
    suggest_type: float
    low: 0.0
    high: 1.0

  - name: target_update_interval
    target: algo_kwargs.target_update_interval
    suggest_type: int
    low: 1
    high: 50

  - name: train_freq
    target: algo_kwargs.train_freq
    suggest_type: int
    low: 1
    high: 50

  - name: gradient_steps
    target: algo_kwargs.gradient_steps
    suggest_type: int
    low: 1
    high: 50

  - name: state_trans_reward_scale
    target: wrapper_kwargs.reward_config.state_trans_reward_scale
    suggest_type: float
    low: 0.01
    high: 100.0
    log: true

  - name: goal_reward_scale
    target: wrapper_kwargs.reward_config.goal_reward_scale
    suggest_type: float
    low: 0.01
    high: 100.0
    log: true
