algo_config:
  algorithm: TD3
  algo_kwargs:
    policy: MultiInputPolicy
    learning_rate: 0.0003
    buffer_size: 1_000_000
    train_freq: 100 # int(batch_size / n_envs) - needs to be calculated
    batch_size: 5000
    gamma: 0.99
    gradient_steps: -1 # -1 means do as many gradient steps as possible in one update
    stats_window_size: 100
    policy_kwargs:
      net_arch: [512, 512, 512]
    verbose: 1

learn_config:
  total_timesteps: 10_000_000
  progress_bar: true

vec_config:
  n_envs: 50
  vec_env_cls: SubprocVecEnv
  vec_env_kwargs: { "start_method": "spawn" }

callback_config:
  eval_callback_config:
    eval_freq: 2_500
    n_eval_episodes: 100
    log_path: eval

  ckpt_callback_config:
    save_freq: 10_000
    save_path: ckpts
    name_prefix: ckpt
    save_replay_buffer: false
    verbose: 0

  video_recorder_callback_config:
    render_freq: 10_000
    save_dir: ckpts
    name_prefix: video
