device: 0
experiment_id: 3.e.m
retrain_model: false
save_config:
  models_dir: out/fr_cont/gcltl/pr
  model_name: gcltl
  model_filname: final_model.zip
  best_model_filename: best_model.zip
  monitor_dir: monitor
  tb_dir: tb
  eval_dir: eval
  eval_metrics_filename: eval.yaml
  animation_dir: animations
  animation_ext: gif
config_dir: configs/fr_cont
env_config_file: env/ang/full_pos_ang_16_vel_5_rand_ag_fix_obj_v2_no_term_250.yaml
wrapper_config_file: gcltl/wrapper/gc_ltl_dense_0.65.yaml
model_config_file: gcltl/rl/ppo_dict_512_10M.yaml
