algo_config:
  algorithm: sb3_soft.SDSAC
  algo_kwargs:
    policy: MultiInputPolicy
    learning_rate: 0.0001
    buffer_size: 1_000_000
    learning_starts: 10000
    batch_size: 2048
    tau: 0.005
    gamma: 0.99
    train_freq: 8
    gradient_steps: 8
    replay_buffer_class: null
    optimize_memory_usage: false
    n_steps: 1 
    ent_coef: auto_0.1
    target_update_interval: 10
    target_entropy: 0.0
    beta: 0.1
    clip_range: 0.5
    stats_window_size: 100    
    policy_kwargs:
      net_arch: [512, 512, 512]
    verbose: 1

learn_config:
  total_timesteps: 20_000_000
  progress_bar: true

vec_config:
  n_envs: 50
  vec_env_cls: SubprocVecEnv
  vec_env_kwargs: { "start_method": "spawn" }

callback_config:
  eval_callback_config:
    eval_freq: 5_000
    n_eval_episodes: 100
    log_path: eval

  ckpt_callback_config:
    save_freq: 200_000
    save_path: ckpts
    name_prefix: ckpt
    save_replay_buffer: false
    verbose: 0

  video_recorder_callback_config:
    render_freq: 20_000
    save_dir: ckpts
    name_prefix: video
