config_class: hrl_tl.config.train.SB3TLHRLTrainingConfig
experiment_id: 3.a.r
gpu_id: 1
retrain_model: false
save_config:
  models_dir: out/fourroom/ltl_hl
  model_name: hl_policy_fourroom
  model_filename: final_model.zip
  monitor_dir: monitor
  tb_dir: tb
config_dir: configs/fourroom
hrl_wrapper_config_file: hrl/2.c.n_tl_hrl_wrapper_pretrained.yaml
env_config_file: env/hard/full_tensor_bl_ag_fix_gl_2_fix_obs_no_obs_term.yaml
rl_config_file: rl/ppo_hrl_tensor_128_5M.yaml
