spec_rep_class: hrl_tl.wrappers.utils.spec_rep.Lv1MinimalSpecRep
spec_rep_args:
  num_clauses: 1
low_level_policy_class: hrl_tl.wrappers.low_level_policies.sb3.SB3Subpolicy
low_level_policy_args:
  config_path: configs/fr_cont/train/baseline/9.c.a_subpolicy_rep0.yaml
  device: cuda:0
  available_devices:
    - cuda:0
max_low_level_policy_steps: 50
all_formulae_file_path: assets/formulae/fourroom/all_formulae_1_cla_1_max_pred_hard.json
invalid_tl_action: random
tl_wrapper_args: configs/fr_cont/gcltl/wrapper/tl_wrapper_0.35.yaml
verbose: false
