spec_rep_class: hrl_tl.wrappers.utils.spec_rep.Lv1MinimalSpecRep
spec_rep_args:
  num_clauses: 1
low_level_policy_class: hrl_tl.wrappers.low_level_policies.gc_ltl.GCLTLLowLevelPolicy
low_level_policy_args:
  model_path: out/fr_cont/gcltl/pr/3.e.m/gcltl_10.0M/best_model.zip
  discrete_state_space: false
  threshold_type: robustness
  switch_threshold: -0.4
  action_sum_coeff: 0.5
  var_value_info_generator_cls: hrl_tl.envs.tl_fourroom.ContRoomsObsVarValueInfoGenerator
  device: cuda:3
  verbose: false
max_low_level_policy_steps: 10
all_formulae_file_path: assets/formulae/fourroom/all_formulae_1_cla_1_max_pred.json
invalid_tl_action: random
tl_wrapper_args: configs/fr_cont/gcltl/wrapper/tl_wrapper_0.6.yaml
verbose: false
