intrinsic_reward_cls: hrl_tl.wrappers.option.intrinsic_rewards.AlloIntrinsicReward
intrinsic_reward_args:
  pipeline_config_path: configs/zone/train/allo/7.g.b_allo_ext.yaml
termination_condition: null
