pipeline_config:
  experiment_id: ""
  device: ""
  retrain_model: false
  save_config:
    models_dir: out/fetch/ablation/subpolicies/12.a.b/rep_0
    model_name: subpolicy_fetch
    model_filename: final_model.zip
    best_model_filename: best_model.zip
    monitor_dir: monitor
    tb_dir: tb
    eval_dir: eval
    eval_metrics_filename: eval.yaml
    animation_dir: animations
    animation_ext: gif
  config_dir: configs/fetch
  env_config_file: env/fetch_reach_avoid_250_0.005_no_term.yaml
  wrapper_config_file: cpc/wrapper/tl_wrapper_abl_tuned.yaml
  model_config_file: rl/sdsac_dict_512_4M_tuned.yaml
