spec_rep_class: hrl_tl.wrappers.utils.spec_rep.ParamLv1MinimalSpecRep
spec_rep_args:
  num_clauses: 1
  args:
    fixed_action_sum_coeff: true
    switch_threshold: { "range": [-45.7, 35.4], "num_discrete_bins": 7 }
low_level_policy_class: hrl_tl.wrappers.low_level_policies.gc_ltl.GCLTLLowLevelPolicy
low_level_policy_args:
  model_path: out/fetch/cpc/pr/5.k.b/cpc_10.0M/rep_1/best_model.zip
  discrete_state_space: false
  action_mode_cls: hrl_tl.envs.fetch.action.FetchMultiDiscreteAction
  action_mode_args:
    num_bins: 5
  device: cuda:0
  verbose: false
max_low_level_policy_steps: 16
all_formulae_file_path: assets/formulae/fetch/cpc/all_formulae_1_cla_1_max_pred.json
invalid_tl_action: random
tl_wrapper_args: configs/fetch/cpc/wrapper/tl_wrapper.yaml
excluded_obs_keys: ["subtask"]
verbose: false
