best_params:
  barrier_init: 0.01
  batch_size: 1000
  gamma_pairs: 0.9
  learning_rate: 2.2427629435385125e-06
  lr_barrier_coeff: 2.1330751823802436e-06
  lr_duals: 1.4312566683230258e-05
  pair_horizon: 100
best_trial_number: 24
best_value: 0.4250259754061699
study_name: allo_pretrain_fr_cont
user_attrs:
  artifact_dir: out/fr_cont/allo/ext/7.d.a/allo_ext_10.0M/optuna_trials/trial_24
  best_model_path: out/fr_cont/allo/ext/7.d.a/allo_ext_10.0M/optuna_trials/trial_24/best_model.zip
  final_model_path: out/fr_cont/allo/ext/7.d.a/allo_ext_10.0M/optuna_trials/trial_24/final_model.zip
