best_params:
  batch_size: 2000
  learning_rate: 0.0002444886467119072
  n_epochs: 20
best_trial_number: 21
best_value: -10.55360414
study_name: gcltl_pr_zone
user_attrs:
  artifact_dir: out/zone/cpc/pr/5.h.a/cpc_40.0M/optuna_trials/trial_21
  best_model_path: out/zone/cpc/pr/5.h.a/cpc_40.0M/optuna_trials/trial_21/best_model.zip
  final_model_path: out/zone/cpc/pr/5.h.a/cpc_40.0M/optuna_trials/trial_21/final_model.zip
