best_params:
  batch_size: 1000
  learning_rate: 0.0008398494803849946
  max_low_level_policy_steps: 11
  n_epochs: 20
  switch_threshold_bins: 39
  switch_threshold_max: 12.376056403917673
  switch_threshold_min: -15.802820379848164
best_trial_number: 5
best_value: 70.07450347999999
study_name: gcltl_hl_zone
user_attrs:
  artifact_dir: out/zone/ltl_hl/5.j.a/hl_policy_zone_1.0M/optuna_trials/trial_5
  best_model_path: out/zone/ltl_hl/5.j.a/hl_policy_zone_1.0M/optuna_trials/trial_5/best_model.zip
  final_model_path: out/zone/ltl_hl/5.j.a/hl_policy_zone_1.0M/optuna_trials/trial_5/final_model.zip
