best_params:
  batch_size: 8000
  learning_rate: 9.244847105841152e-05
  n_epochs: 20
best_trial_number: 24
best_value: -0.50506
study_name: ppo_zone
user_attrs:
  artifact_dir: out/zone/ppo/6.e.a/ppo_zone_30.0M/optuna_trials/trial_24
  best_model_path: out/zone/ppo/6.e.a/ppo_zone_30.0M/optuna_trials/trial_24/best_model.zip
  final_model_path: out/zone/ppo/6.e.a/ppo_zone_30.0M/optuna_trials/trial_24/final_model.zip
