best_params:
  batch_size: 3000
  clip_range: 0.2527896185195276
  ent_coef: 0.012778371073181038
  learning_rate: 0.000517963728942035
  max_low_level_policy_steps: 29
  n_epochs: 30
best_trial_number: 16
best_value: 47.920743079999994
study_name: spec_cond_hl_fetch
user_attrs:
  artifact_dir: out/fetch/spec_cond/meta//15.b.a/hl_policy_fetch_tune_2.0M/optuna_trials/trial_16
  best_model_path: out/fetch/spec_cond/meta//15.b.a/hl_policy_fetch_tune_2.0M/optuna_trials/trial_16/best_model.zip
  final_model_path: out/fetch/spec_cond/meta//15.b.a/hl_policy_fetch_tune_2.0M/optuna_trials/trial_16/final_model.zip
