max_episode_steps: 250
option_policy_class: stable_baselines3.PPO
option_policy_dir: out/zone/allo/subpolicies/7.h.b/rep_0
option_policy_name: final_model
device: cuda:0
reward_type: smdp
gamma: 0.99
invalid_option_penalty: -1.0
include_random_option: true
random_option_termination_steps: 1
capture_primitive_transitions: null
max_option_steps: 39
include_step_count_in_obs: false
