config_class: hrl_tl.config.train.SB3LowLevelTrainingConfig
gpu_id: 0
retrain_model: false
save_config:
  models_dir: "out/fourroom/primitives/tensor"
  model_name: "fourroom_tl_prim_ppo_tensor"
  model_filename: "final_model.zip"
  monitor_dir: "monitor"
  tb_dir: "tb"
config_dir: "configs/fourroom"
env_config_file: "env/full_tensor_rand.yaml"
rl_config_file: "rl/ppo_tl.yaml"
tl_wrapper_config_file: "rl/tl_wrapper.yaml"
