device: 3
retrain_model: false
save_config:
  models_dir: out/fourroom/gcltl/pr/3.d.a/eval
  model_name: gcltl_comp
  model_filname: final_model.zip
  best_model_filename: best_model.zip
  monitor_dir: monitor
  tb_dir: tb
  eval_dir: eval
  eval_metrics_filename: eval.yaml
  animation_dir: animations
  animation_ext: gif
config_dir: configs/fourroom
env_config_file: env/hard/full_tensor_fix_ag_fix_gl_2_fix_obs.yaml
model_config_file: gcltl/rl/ppo_dict_128_1M.yaml
wrapper_config_file: gcltl/wrapper/tl_wrapper.yaml
