goal_pred_name: psi_lv
predicates:
  - { "name": "psi_ld", "formula": "d_ld < 0.35", num_entities: 1 }
  - { "name": "psi_bd", "formula": "d_bd < 0.35", num_entities: 1 }
  - { "name": "psi_td", "formula": "d_td < 0.35", num_entities: 1 }
  - { "name": "psi_rd", "formula": "d_rd < 0.35", num_entities: 1 }
  - { "name": "psi_gl", "formula": "d_gl < 0.35", num_entities: 1 }
  - { "name": "psi_lv", "formula": "d_lv_c < 0.35", num_entities: 16 }
  - { "name": "psi_hl", "formula": "d_hl_c < 0.35", num_entities: 16 }
var_value_info_generator_cls: hrl_tl.envs.tl_fourroom.ContRoomsVarValueInfoGenerator
early_termination: true
reward_type: dense
dense_reward_scale: 1.0
goal_rep: one_hot
